runtime: nodejs
env: flex
# handlers:
# - url: /
#   static_files: dist/index.html
#   upload: dist/index.html

# - url: /dist/(.*)
#   static_files: dist/\1
#   upload: dist/(.*)

env_variables:
  NODE_ENV: "production"
  MONGODB: "mongodb://10.142.0.3:27017/goods"